---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: CAS

spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65100
    # Overlay loopback IP and same pool can be assigned to both spine and l3leaf switches
    # If same loopback pool is defined for both spine and l3leaf,
    # < loopback_ipv4_offset > must be set in either one of the node_types
    loopback_ipv4_pool: 172.31.210.0/24
  nodes:
    spine1-CAS:
      id: 1
      mgmt_ip: 198.18.107.211/23
    spine2-CAS:
      id: 2
      mgmt_ip: 198.18.107.212/23

l3leaf:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65100
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    # VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
    # Assign range larger than total leaf switches
    vtep_loopback_ipv4_pool: 172.31.211.0/24
    loopback_ipv4_pool: 172.30.211.0/24
    # Offset must be >= number of spines
    loopback_ipv4_offset: 2
    # Point to Point Network Summary range, assigned as /31 for each
    # uplink interfaces
    # Assign range larger than total [spines * total potential leafs * 2]
    uplink_ipv4_pool: 172.21.211.0/24
    uplink_switches: [spine1-CAS, spine2-CAS]
    uplink_interfaces: [Ethernet3, Ethernet4]
    mlag_interfaces: [Ethernet1, Ethernet2]
    # mlag pair IP assignment - assign blocks - Assign range larger than
    # total spines + total leafs switches
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    CAS_BORDERLEAFS:
      bgp_as: 65110
      nodes:
        borderleaf1-CAS:
          id: 1
          mgmt_ip: 198.18.107.213/23
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        borderleaf2-CAS:
          id: 2
          mgmt_ip: 198.18.107.214/23
          uplink_switch_interfaces: [Ethernet6, Ethernet6]
    CAS_POD1:
      bgp_as: 65111
      nodes:
        leaf1-CAS:
          id: 3
          mgmt_ip: 198.18.107.215/23
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        leaf2-CAS:
          id: 4
          mgmt_ip: 198.18.107.216/23
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    CAS_POD2:
      bgp_as: 65112
      nodes:
        leaf3-CAS:
          id: 5
          mgmt_ip: 198.18.107.217/23
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        leaf4-CAS:
          id: 6
          mgmt_ip: 198.18.107.218/23
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
    CAS_DCI:
      bgp_as: 65110
      nodes:
        borderleaf1-CAS:
          id: 7
          mgmt_ip: 198.18.107.213/23
          uplink_switches: [borderleaf1-OI]
          uplink_interfaces: [Ethernet5]
          uplink_switch_interfaces: [Ethernet5]
        borderleaf2-CAS:
          id: 8
          mgmt_ip: 198.18.107.214/23
          uplink_switches: [borderleaf2-OI]
          uplink_interfaces: [Ethernet5]
          uplink_switch_interfaces: [Ethernet5]

# Disable update wait-for-convergence and update wait-for-install, which is not supported in vEOS-LAB.
spine_bgp_defaults:
#  - update wait-for-convergence
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

# Update p2p mtu 9000 -> 1500, MTU 9000 not supported in vEOS-LAB.
p2p_uplinks_mtu: 1500

# Adjust default bfd values, to avoid high CPU.
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
