---
port_profiles:
  ALL:
    mode: trunk
    vlans: "160,161,1110-1111,1120-1121,1130-1131,1140,1210-1211,1250"
  ACCESS:
    mode: access
    vlans: "160"
  L3_NET:
    mode: trunk
    vlans: "1110-1111,1120-1121,1130-1131,1140,1210-1211,1250"

servers:
  POD1:
    rack: POD1
    adapters:
      - type: nic
        server_ports: [Eth0,Eth1]
        switch_ports: [Ethernet5,Ethernet5]
        switches: [leaf1-CAS,leaf2-CAS]
        profile: ALL
  POD2:
    rack: POD2
    adapters:
      - type: nic
        server_ports: [Eth0,Eth1]
        switch_ports: [Ethernet5,Ethernet5]
        switches: [leaf3-CAS,leaf4-CAS]
        profile: ALL
  BORDER1:
    rack: BORDER1
    adapters:
      - type: nic
        server_ports: [Eth0,Eth1]
        switch_ports: [Ethernet6,Ethernet6]
        switches: [borderleaf1-CAS,borderleaf2-CAS]
        profile: L3_NET