---
port_profiles:
  VLANS_INTERNA:
    mode: trunk
    vlans: "100,101,102,1110"
  CLIENTE_ACCESS:
    mode: access
    vlans: "1111"
  CLIENTE_TRUNK:
    mode: trunk
    vlans: "1111"

servers:
  HOST1:
    rack: POD1
    adapters:
      - type: nic
        server_ports: [Eth0,Eth1]
        switch_ports: [Ethernet5,Ethernet5]
        switches: [leaf1-CAS,leaf2-CAS]
        profile: CLIENTE_TRUNK
        port_channel:
        # Po interface number follows the first interface port number
          state: present
          description: PortChannel
          mode: active
  HOST2:
    rack: POD2
    adapters:
      - type: nic
        server_ports: [Eth0,Eth1]
        switch_ports: [Ethernet5,Ethernet5]
        switches: [leaf3-CAS,leaf4-CAS]
        profile: CLIENTE_TRUNK
        port_channel:
          state: present
          description: PortChannel Acesso
          mode: active
  BORDER1:
    rack: BORDER1
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet6]
        switches: [borderleaf1-CAS]
        profile: VLANS_INTERNA
        # port_channel:
        #   state: present
        #   description: PortChannel Servico
        #   mode: active
    rack: BORDER2
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet6]
        switches: [borderleaf2-CAS]
        profile: VLAN_CLUSTER