---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: OI_FABRIC

spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65200
    # Overlay loopback IP and same pool can be assigned to both spine and l3leaf switches
    # If same loopback pool is defined for both spine and l3leaf,
    # < loopback_ipv4_offset > must be set in either one of the node_types
    loopback_ipv4_pool: 172.31.220.0/24
  nodes:
    spine1-OI:
      id: 1
      mgmt_ip: 198.18.107.221/23
    spine2-OI:
      id: 2
      mgmt_ip: 198.18.107.222/23

l3leaf:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65200
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:02
    # VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
    # Assign range larger than total leaf switches
    vtep_loopback_ipv4_pool: 172.31.221.0/24
    loopback_ipv4_pool: 172.30.221.0/24
    # Offset must be >= number of spines
    loopback_ipv4_offset: 2
    # Point to Point Network Summary range, assigned as /31 for each
    # uplink interfaces
    # Assign range larger than total [spines * total potential leafs * 2]
    uplink_ipv4_pool: 172.21.221.0/24
    uplink_switches: [spine1-OI, spine2-OI]
    uplink_interfaces: [Ethernet3, Ethernet4]
    mlag_interfaces: [Ethernet1, Ethernet2]
    # mlag pair IP assignment - assign blocks - Assign range larger than
    # total spines + total leafs switches
    mlag_peer_ipv4_pool: 10.255.248.0/24
    mlag_peer_l3_ipv4_pool: 10.255.247.0/24
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    OI_BORDERLEAFS:
      bgp_as: 65210
      nodes:
        borderleaf1-OI:
          id: 1
          mgmt_ip: 192.18.107.223/23
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        borderleaf2-OI:
          id: 2
          mgmt_ip: 192.18.107.224/23
          uplink_switch_interfaces: [Ethernet6, Ethernet6]
    OI_POD1:
      bgp_as: 65211
      nodes:
        leaf1-OI:
          id: 1
          mgmt_ip: 192.18.107.225/23
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        leaf2-OI:
          id: 2
          mgmt_ip: 192.18.107.226/23
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    OI_POD2:
      bgp_as: 65212
      nodes:
        leaf3-OI:
          id: 3
          mgmt_ip: 192.18.107.227/23
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        leaf4-OI:
          id: 4
          mgmt_ip: 192.18.107.228/23
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

# Disable update wait-for-convergence and update wait-for-install, which is not supported in vEOS-LAB.
spine_bgp_defaults:
#  - update wait-for-convergence
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
#  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

# Update p2p mtu 9000 -> 1500, MTU 9000 not supported in vEOS-LAB.
p2p_uplinks_mtu: 1500

# Adjust default bfd values, to avoid high CPU.
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

