---
# DC Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant FrontEnd Specific Information - VRFs / VLANs
  FrontEnd:
    mac_vrf_vni_base: 21000
    vrfs:
      FW_Outside:
        vrf_vni: 111
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.2.0/24
        svis:
          #FW_OUTSIDE_VLAN
          1110:
            vni_override: 50110
            name: FrontEnd_OP_Zone_1
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.110.1/24
          #CLIENT_OUTSIDE_VLAN
          1111:
            vni_override: 50111
            name: FrontEnd_OP_Zone_2
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.111.1/24
    l2vlans:
      # CLUSTER
      100:
        vni_override: 55100
        name: FW_CLUSTER
        tags: [cluster]
      # INTERNA
      101:
        vni_override: 55101
        name: FW_INTERNA
        tags: [interna]
      # SERVICO
      102:
        vni_override: 55102
        name: FW_SERVICO
        tags: [servico]
  # Tenant BackEnd Specific Information - VRFs / VLANs
  # BackEnd:
  #   mac_vrf_vni_base: 22000
  #   vrfs:
  #     BackEnd_OP_Zone:
  #       vrf_vni: 221
  #       svis:
  #         2210:
  #           name: BackEnd_OP_Zone_1
  #           tags: [opzone]
  #           enabled: true
  #           ip_address_virtual: 10.2.210.1/24
  #         2211:
  #           name: BackEnd_OP_Zone_2
  #           tags: [opzone]
  #           enabled: true
  #           ip_address_virtual: 10.2.211.1/24
  #     BackEnd_DB_Zone:
  #       vrf_vni: 225
  #       svis:
  #         2250:
  #           name: BackEnd_DB_Zone_1
  #           tags: [db]
  #           enabled: true
  #           ip_address_virtual: 10.2.250.1/24