---
# DC Tenants Networks
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  # Tenant FrontEnd Specific Information - VRFs / VLANs
  FrontEnd:
    mac_vrf_vni_base: 21000
    vrfs:
      FrontEnd_OP_Zone:
        vrf_vni: 211
        vtep_diagnostic:
          loopback: 200
          loopback_ip_range: 10.255.2.0/24
        svis:
          2110:
            name: FrontEnd_OP_Zone_1
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.2.110.1/24
          2111:
            vni_override: 50111
            name: FrontEnd_OP_Zone_2
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.2.111.1/24
      FrontEnd_WEB_Zone:
        vrf_vni: 212
        svis:
          2120:
            name: FrontEnd_WEB_Zone_1
            tags: [web, erp1]
            enabled: true
            # ip_subnet: 10.2.30.0/24
            #< now ip_address_virtual and required to provide gateway ip as opposed to network.>
            ip_address_virtual: 10.2.120.1/24
          2121:
            name: FrontEnt_WEB_Zone_2
            tags: [web]
            enabled: true
            ip_address_virtual: 10.2.121.1/24
      FrontEnd_APP_Zone:
        vrf_vni: 213
        svis:
          2130:
            name: FrontEnt_APP_Zone_1
            tags: [app, erp1]
            enabled: true
            ip_address_virtual: 10.2.130.1/24
            
          2131:
            name: FrontEnd_APP_Zone_2
            tags: [app]
            enabled: true
            ip_address_virtual: 10.2.131.254/24
      FrontEnd_WAN_Zone:
        vrf_vni: 214
        svis:
          2140:
            name: FrontEnd_WAN_Zone_1
            tags: [wan]
            enabled: true
            ip_address_virtual: 10.2.140.1/24
    l2vlans:
      160:
        vni_override: 55160
        name: FrontEnd_VMOTION
        tags: [vmotion]
      161:
        name: FrontEnd_NFS
        tags: [nfs]

  # Tenant BackEnd Specific Information - VRFs / VLANs
  BackEnd:
    mac_vrf_vni_base: 22000
    vrfs:
      BackEnd_OP_Zone:
        vrf_vni: 221
        svis:
          2210:
            name: BackEnd_OP_Zone_1
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.2.210.1/24
          2211:
            name: BackEnd_OP_Zone_2
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.2.211.1/24
      BackEnd_DB_Zone:
        vrf_vni: 225
        svis:
          2250:
            name: BackEnd_DB_Zone_1
            tags: [db]
            enabled: true
            ip_address_virtual: 10.2.250.1/24