router_bgp:
  as: '65200'
  router_id: 172.31.220.2
  bgp_defaults:
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      ebgp_multihop: '3'
      send_community: all
      maximum_routes: 0
      next_hop_unchanged: true
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    172.21.221.11:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65211'
      description: leaf1-OI_Ethernet4
    172.21.221.15:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65211'
      description: leaf2-OI_Ethernet4
    172.21.221.19:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65212'
      description: leaf3-OI_Ethernet4
    172.21.221.23:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65212'
      description: leaf4-OI_Ethernet4
    172.21.221.3:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65210'
      description: borderleaf1-OI_Ethernet4
    172.21.221.7:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65210'
      description: borderleaf2-OI_Ethernet4
    172.30.221.3:
      peer_group: EVPN-OVERLAY-PEERS
      description: borderleaf1-OI
      remote_as: '65210'
    172.30.221.4:
      peer_group: EVPN-OVERLAY-PEERS
      description: borderleaf2-OI
      remote_as: '65210'
    172.30.221.5:
      peer_group: EVPN-OVERLAY-PEERS
      description: leaf1-OI
      remote_as: '65211'
    172.30.221.6:
      peer_group: EVPN-OVERLAY-PEERS
      description: leaf2-OI
      remote_as: '65211'
    172.30.221.7:
      peer_group: EVPN-OVERLAY-PEERS
      description: leaf3-OI
      remote_as: '65212'
    172.30.221.8:
      peer_group: EVPN-OVERLAY-PEERS
      description: leaf4-OI
      remote_as: '65212'
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 198.18.106.1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 208.67.222.222
  - 8.8.8.8
spanning_tree:
  mode: none
local_users:
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$k2QzB8961/dFJf35$HLuhZBTypOM05zmGx99BAHI0.Zok8GUVm303zaZTJhQmp.cKq84un1e.cqztvC8ZFqRN6bCc.GkOknMBurXki.
  netadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$cK1bIDtMtCcnZC.1$/WgQmDoQ4pv4et2vYjX8M65SW667tVQreVBItTinbqOLP4Ef41bSt8rKLoLJMvwYLSw7gVJJMxUBdL1jagQ.9.
vrfs:
  MGMT:
    ip_routing: false
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 198.18.107.222/23
    gateway: 198.18.106.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: {}
  enable_https: true
ethernet_interfaces:
  Ethernet1:
    peer: leaf1-OI
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: P2P_LINK_TO_LEAF1-OI_Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.221.10/31
  Ethernet2:
    peer: leaf2-OI
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: P2P_LINK_TO_LEAF2-OI_Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.221.14/31
  Ethernet3:
    peer: leaf3-OI
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: P2P_LINK_TO_LEAF3-OI_Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.221.18/31
  Ethernet4:
    peer: leaf4-OI
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: P2P_LINK_TO_LEAF4-OI_Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.221.22/31
  Ethernet5:
    peer: borderleaf1-OI
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: P2P_LINK_TO_BORDERLEAF1-OI_Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.221.2/31
  Ethernet6:
    peer: borderleaf2-OI
    peer_interface: Ethernet4
    peer_type: l3leaf
    description: P2P_LINK_TO_BORDERLEAF2-OI_Ethernet4
    mtu: 1500
    type: routed
    shutdown: false
    ip_address: 172.21.221.6/31
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 172.31.220.2/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 172.31.220.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
